# Generated by Django 5.2.17 on 2026-09-22 06:26

import apps.memberships.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0003_customer_code_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Monthly Gold', max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Struck-through price, for showing what the scheme saves.', max_digits=9, null=True)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='How long one term runs. 30 for a monthly scheme.', validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Standing discount a member gets on sessions. Shown at the counter; staff still apply it at checkout.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('included_hours', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Play hours the term includes. 0 for a discount-only scheme.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, max_length=180)),
                ('perks', models.TextField(blank=True, help_text='One perk per line. Listed on the plan card.')),
                ('badge', models.CharField(blank=True, help_text='e.g. Popular, Best value', max_length=24)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop selling it without touching live members.')),
                ('is_public', models.BooleanField(default=True, help_text='Show this scheme on the public site.')),
                ('station_types', models.ManyToManyField(blank=True, help_text='Which platforms the scheme covers. Leave empty for all of them.', related_name='membership_plans', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('sort_order', 'price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.memberships.models.make_membership_code, editable=False, max_length=12, unique=True)),
                ('plan_name', models.CharField(blank=True, max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='What this term was sold for.', max_digits=9)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('included_hours', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('starts_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='unpaid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hours_used', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Play hours drawn from the term, if the scheme includes any.', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan')),
            ],
            options={
                'ordering': ('-starts_on', '-created_at'),
                'indexes': [models.Index(fields=['status', 'ends_on'], name='memberships_status_6018ce_idx')],
            },
        ),
    ]
