# Generated by Django 5.2.17 on 2026-09-22 07:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_discount_reason_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text="Roll into a fresh term when this one ends, priced at the plan's rate on the day it rolls. The fee is still collected by hand."),
        ),
        migrations.AddField(
            model_name='membership',
            name='paused_days',
            field=models.PositiveIntegerField(default=0, help_text='Total days this term has been frozen for, across all pauses.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='paused_on',
            field=models.DateField(blank=True, help_text='The day the term was frozen. Null when running.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='renewed_from',
            field=models.ForeignKey(blank=True, help_text='The term this one followed, so a subscription reads as a chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='hours_used',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Play hours drawn from the term. A cached sum of the usage ledger.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='MembershipUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=1, help_text='Positive draws from the allowance, negative gives hours back.', max_digits=6)),
                ('kind', models.CharField(choices=[('session', 'Session played'), ('adjustment', 'Manual adjustment'), ('credit', 'Hours credited back')], default='session', max_length=12)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('booking', models.OneToOneField(blank=True, help_text='The session this draw came from. A booking draws exactly once.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_usage', to='bookings.booking')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Membership usage',
                'verbose_name_plural': 'Membership usage',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
