# Generated by Django 5.2.17 on 2026-09-01 06:50

import apps.bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('opens_at', models.TimeField(default='10:00')),
                ('closes_at', models.TimeField(default='23:00')),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Business hours',
                'ordering': ('weekday',),
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('is_full_day', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.bookings.models.make_booking_code, editable=False, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('seats', models.PositiveSmallIntegerField(default=1, help_text='How many stations of this type the booking holds.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='pending', max_length=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid at counter'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('source', models.CharField(choices=[('website', 'Website'), ('walkin', 'Walk-in'), ('phone', 'Phone')], default='website', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customers.customer')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.pricingplan')),
                ('station', models.ForeignKey(blank=True, help_text='Assigned by staff. Leave blank until check-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.station')),
                ('station_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('-start_at',),
                'indexes': [models.Index(fields=['start_at', 'status'], name='bookings_bo_start_a_44a703_idx')],
            },
        ),
    ]
