# Generated by Django 5.2.17 on 2026-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_backfill_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual discount applied at checkout. Always a rupee figure.', max_digits=9),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Why it was given. Required whenever a discount is applied.', max_length=140),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other'), ('split', 'Split')], help_text='How the money was taken. Blank until payment is recorded.', max_length=10),
        ),
    ]
