# Generated by Django 5.2.17 on 2026-09-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_discount_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='controllers',
            field=models.PositiveSmallIntegerField(default=1, help_text='Controllers in use on each station, for a console priced per controller. Ignored by station types priced per seat.'),
        ),
    ]
