# Generated by Django 5.2.17 on 2026-09-01 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('topic', models.CharField(choices=[('general', 'General enquiry'), ('booking', 'Booking help'), ('tournament', 'Tournaments'), ('party', 'Private / party booking'), ('feedback', 'Feedback')], default='general', max_length=12)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=180)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(choices=[('setup', 'The setup'), ('events', 'Events'), ('squad', 'Squad'), ('cafe', 'The space')], default='setup', max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Bonfire Gaming Hub', max_length=80)),
                ('tagline', models.CharField(default='Where the game never dies out.', max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('hero_eyebrow', models.CharField(blank=True, default='Now open', max_length=60)),
                ('hero_headline', models.CharField(default='Fuel the fire.', max_length=120)),
                ('hero_subline', models.CharField(default='High-spec gaming PCs and PS5s, weekly tournaments, and a room built for squads.', max_length=240)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('hero_cta_label', models.CharField(default='Book a station', max_length=40)),
                ('about_heading', models.CharField(default='Built by gamers, for gamers', max_length=120)),
                ('about_body', models.TextField(blank=True)),
                ('announcement', models.CharField(blank=True, help_text='Ticker at the top of the public site. Blank hides it.', max_length=200)),
                ('announcement_is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=140)),
                ('address_line2', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed src URL.')),
                ('directions_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('booking_lead_minutes', models.PositiveSmallIntegerField(default=30, help_text='Earliest a customer may book from now.')),
                ('booking_horizon_days', models.PositiveSmallIntegerField(default=14, help_text='How far ahead the public may book.')),
                ('booking_note', models.CharField(blank=True, default='Pay at the counter when you arrive. Hold expires 15 minutes after slot start.', max_length=200)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='brand/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('handle', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
