# Generated by Django 5.2.17 on 2026-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text="Google Maps link for the shop. A share link (maps.app.goo.gl) is fine — it is used for the 'open in Maps' buttons. Google will not display share links inside a frame, so the embedded map falls back to a search on the address above. For the exact pin in the embed, paste the src from Maps > Share > Embed a map.", max_length=500),
        ),
    ]
