# Generated by Django 5.2.17 on 2026-09-10 06:55

import apps.shop.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_backfill_codes'),
        ('customers', '0003_customer_code_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('icon', models.CharField(default='star', help_text='Icon key rendered by the admin (star, flame, gamepad, monitor, wheel, vr).', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CounterSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.shop.models.make_sale_code, editable=False, max_length=12, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Optional for a walk-in.', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='paid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sales', to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, help_text='Optional shelf or barcode label.', max_length=40)),
                ('kind', models.CharField(choices=[('consumable', 'Consumable (snacks, drinks)'), ('rental', 'Rental (kit that comes back)')], default='consumable', max_length=12)),
                ('pricing_mode', models.CharField(choices=[('flat', 'Flat charge'), ('hourly', 'Per hour of the session')], default='flat', help_text='Hourly items multiply by the length of the session they are added to.', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, max_length=180)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('track_stock', models.BooleanField(default=True, help_text='Uncheck for something you never run out of.')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Consumables: units on the shelf. Rentals: units owned.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Flag the item in the admin at or below this count.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.productcategory')),
            ],
            options={
                'ordering': ('category__sort_order', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.IntegerField(help_text='Positive to add stock, negative to remove.')),
                ('reason', models.CharField(choices=[('restock', 'Restocked'), ('correction', 'Count correction'), ('damage', 'Damaged or lost'), ('return', 'Returned to supplier')], default='restock', max_length=12)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('resulting_stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='shop.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pricing_mode', models.CharField(choices=[('flat', 'Flat charge'), ('hourly', 'Per hour of the session')], max_length=8)),
                ('kind', models.CharField(choices=[('consumable', 'Consumable (snacks, drinks)'), ('rental', 'Rental (kit that comes back)')], max_length=12)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Billable hours for an hourly item.', max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('returned_at', models.DateTimeField(blank=True, help_text='When a rental came back. Null means it is still out.', null=True)),
                ('staff_notes', models.CharField(blank=True, max_length=140)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.countersale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='shop.product')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('sale__isnull', True)), models.Q(('booking__isnull', True), ('sale__isnull', False)), _connector='OR'), name='bill_item_belongs_to_exactly_one_bill')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_product_name_per_category'),
        ),
    ]
