# Generated by Django 5.2.17 on 2026-09-12 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_discount_reason_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='countersale',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='countersale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other'), ('split', 'Split')], max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('settled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the money actually moved.')),
                ('note', models.CharField(blank=True, max_length=140)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.countersale')),
            ],
            options={
                'ordering': ('settled_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('sale__isnull', True)), models.Q(('booking__isnull', True), ('sale__isnull', False)), _connector='OR'), name='payment_belongs_to_exactly_one_bill')],
            },
        ),
    ]
