# Generated by Django 5.2.17 on 2026-09-01 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='monitor', help_text='Icon key rendered by the frontend (monitor, gamepad, wheel, vr, headset).', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='station-types/')),
                ('max_players_per_station', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. PC-01, PS5-02', max_length=40, unique=True)),
                ('specs', models.TextField(blank=True, help_text='CPU / GPU / RAM / monitor, or console details.')),
                ('peripherals', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='available', max_length=20)),
                ('status_note', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
                ('is_bookable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('station_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('station_type__sort_order', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. 1 Hour, Happy Hour, 5-Hour Pack', max_length=60)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Struck-through price, for showing a discount.', max_digits=8, null=True)),
                ('badge', models.CharField(blank=True, help_text='e.g. Popular, Best value', max_length=24)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('available_from', models.TimeField(blank=True, help_text='Happy-hour window start.', null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('station_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('station_type__sort_order', 'sort_order', 'duration_minutes'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('genre', models.CharField(blank=True, max_length=60)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('-is_featured', 'sort_order', 'title'),
            },
        ),
    ]
