# Generated by Django 5.2.17 on 2026-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Offer this plan in the online booking flow. Uncheck for a rate that is advertised but only sold at the counter — a happy-hour deal, say, where the discount depends on when you actually turn up.'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this rate on the public site.'),
        ),
    ]
