# Generated by Django 5.2.17 on 2026-09-28 06:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_windowed_plans_are_not_bookable'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtype',
            name='prices_per_controller',
            field=models.BooleanField(default=False, help_text='Charge by controller rather than by station. A console seats a group on one screen, so the rate is set per controller and drops as more join.'),
        ),
        migrations.AlterField(
            model_name='stationtype',
            name='max_players_per_station',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many people share one station. For a console priced per controller, this is the most controllers one unit takes.'),
        ),
        migrations.CreateModel(
            name='ControllerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controllers', models.PositiveSmallIntegerField(help_text='How many controllers are in use.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_controller', models.DecimalField(decimal_places=2, help_text='Charged for each controller at this group size.', max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_rates', to='catalog.pricingplan')),
            ],
            options={
                'ordering': ('plan', 'controllers'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'controllers'), name='unique_rate_per_group_size')],
            },
        ),
    ]
