# Generated by Django 5.2.17 on 2026-09-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('game', models.CharField(help_text='e.g. Valorant, FIFA 26, BGMI', max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('single_elim', 'Single elimination'), ('double_elim', 'Double elimination'), ('round_robin', 'Round robin'), ('points', 'Points / leaderboard')], default='single_elim', max_length=20)),
                ('team_size', models.PositiveSmallIntegerField(default=1, help_text='1 for solo events.')),
                ('max_teams', models.PositiveSmallIntegerField(default=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('prize_breakdown', models.TextField(blank=True, help_text="One prize per line, e.g. '1st - Rs 3000'")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Registration open'), ('full', 'Full'), ('live', 'Live now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('is_recurring_weekly', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('venue_note', models.CharField(blank=True, max_length=160)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='catalog.stationtype')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=80)),
                ('captain_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('roster', models.TextField(blank=True, help_text='One player per line: name / in-game ID.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waitlist', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid at counter'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_registrations', to='customers.customer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ('tournament', 'seed', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('tournament', 'phone'), name='unique_registration_per_phone')],
            },
        ),
    ]
