# Generated by Django 5.2.17 on 2026-09-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entry fee actually collected.', max_digits=8),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10),
        ),
    ]
