# Generated by Django 5.2.17 on 2026-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gamer_tag', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('walkin', 'Walk-in'), ('member', 'Member'), ('vip', 'VIP'), ('banned', 'Banned')], default='walkin', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
